// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxhtmlnp.proxies;

public class HTMLDocument
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject hTMLDocumentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxHTMLNP.HTMLDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Id("_Id"),
		HTMLDocument_SessionData("MxHTMLNP.HTMLDocument_SessionData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HTMLDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxHTMLNP.HTMLDocument"));
	}

	protected HTMLDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject hTMLDocumentMendixObject)
	{
		if (hTMLDocumentMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxHTMLNP.HTMLDocument", hTMLDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxHTMLNP.HTMLDocument");

		this.hTMLDocumentMendixObject = hTMLDocumentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'HTMLDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxhtmlnp.proxies.HTMLDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxhtmlnp.proxies.HTMLDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxhtmlnp.proxies.HTMLDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxhtmlnp.proxies.HTMLDocument(context, mendixObject);
	}

	public static mxhtmlnp.proxies.HTMLDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxhtmlnp.proxies.HTMLDocument.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _Id
	 */
	public final java.lang.Integer get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.Integer get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.Integer _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return value of HTMLDocument_SessionData
	 */
	public final mxhtmlnp.proxies.SessionData getHTMLDocument_SessionData() throws com.mendix.core.CoreException
	{
		return getHTMLDocument_SessionData(getContext());
	}

	/**
	 * @param context
	 * @return value of HTMLDocument_SessionData
	 */
	public final mxhtmlnp.proxies.SessionData getHTMLDocument_SessionData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxhtmlnp.proxies.SessionData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HTMLDocument_SessionData.toString());
		if (identifier != null)
			result = mxhtmlnp.proxies.SessionData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of HTMLDocument_SessionData
	 * @param htmldocument_sessiondata
	 */
	public final void setHTMLDocument_SessionData(mxhtmlnp.proxies.SessionData htmldocument_sessiondata)
	{
		setHTMLDocument_SessionData(getContext(), htmldocument_sessiondata);
	}

	/**
	 * Set value of HTMLDocument_SessionData
	 * @param context
	 * @param htmldocument_sessiondata
	 */
	public final void setHTMLDocument_SessionData(com.mendix.systemwideinterfaces.core.IContext context, mxhtmlnp.proxies.SessionData htmldocument_sessiondata)
	{
		if (htmldocument_sessiondata == null)
			getMendixObject().setValue(context, MemberNames.HTMLDocument_SessionData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.HTMLDocument_SessionData.toString(), htmldocument_sessiondata.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return hTMLDocumentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxhtmlnp.proxies.HTMLDocument that = (mxhtmlnp.proxies.HTMLDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxHTMLNP.HTMLDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
