// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxhtmlnp.proxies;

public class Node
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxHTMLNP.Node";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Content("Content"),
		Node_HTMLDocument("MxHTMLNP.Node_HTMLDocument"),
		Children("MxHTMLNP.Children"),
		Node_Attribute("MxHTMLNP.Node_Attribute");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Node(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxHTMLNP.Node"));
	}

	protected Node(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nodeMendixObject)
	{
		if (nodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxHTMLNP.Node", nodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxHTMLNP.Node");

		this.nodeMendixObject = nodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Node.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxhtmlnp.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxhtmlnp.proxies.Node.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxhtmlnp.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxhtmlnp.proxies.Node(context, mendixObject);
	}

	public static mxhtmlnp.proxies.Node load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxhtmlnp.proxies.Node.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of Node_HTMLDocument
	 */
	public final java.util.List<mxhtmlnp.proxies.HTMLDocument> getNode_HTMLDocument() throws com.mendix.core.CoreException
	{
		return getNode_HTMLDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_HTMLDocument
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mxhtmlnp.proxies.HTMLDocument> getNode_HTMLDocument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mxhtmlnp.proxies.HTMLDocument> result = new java.util.ArrayList<mxhtmlnp.proxies.HTMLDocument>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Node_HTMLDocument.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(mxhtmlnp.proxies.HTMLDocument.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Node_HTMLDocument
	 * @param node_htmldocument
	 */
	public final void setNode_HTMLDocument(java.util.List<mxhtmlnp.proxies.HTMLDocument> node_htmldocument)
	{
		setNode_HTMLDocument(getContext(), node_htmldocument);
	}

	/**
	 * Set value of Node_HTMLDocument
	 * @param context
	 * @param node_htmldocument
	 */
	public final void setNode_HTMLDocument(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mxhtmlnp.proxies.HTMLDocument> node_htmldocument)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (mxhtmlnp.proxies.HTMLDocument proxyObject : node_htmldocument)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Node_HTMLDocument.toString(), identifiers);
	}

	/**
	 * @return value of Children
	 */
	public final java.util.List<mxhtmlnp.proxies.Node> getChildren() throws com.mendix.core.CoreException
	{
		return getChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of Children
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mxhtmlnp.proxies.Node> getChildren(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mxhtmlnp.proxies.Node> result = new java.util.ArrayList<mxhtmlnp.proxies.Node>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Children.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(mxhtmlnp.proxies.Node.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Children
	 * @param children
	 */
	public final void setChildren(java.util.List<mxhtmlnp.proxies.Node> children)
	{
		setChildren(getContext(), children);
	}

	/**
	 * Set value of Children
	 * @param context
	 * @param children
	 */
	public final void setChildren(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mxhtmlnp.proxies.Node> children)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (mxhtmlnp.proxies.Node proxyObject : children)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Children.toString(), identifiers);
	}

	/**
	 * @return value of Node_Attribute
	 */
	public final java.util.List<mxhtmlnp.proxies.Attribute> getNode_Attribute() throws com.mendix.core.CoreException
	{
		return getNode_Attribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_Attribute
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mxhtmlnp.proxies.Attribute> getNode_Attribute(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mxhtmlnp.proxies.Attribute> result = new java.util.ArrayList<mxhtmlnp.proxies.Attribute>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Node_Attribute.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(mxhtmlnp.proxies.Attribute.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Node_Attribute
	 * @param node_attribute
	 */
	public final void setNode_Attribute(java.util.List<mxhtmlnp.proxies.Attribute> node_attribute)
	{
		setNode_Attribute(getContext(), node_attribute);
	}

	/**
	 * Set value of Node_Attribute
	 * @param context
	 * @param node_attribute
	 */
	public final void setNode_Attribute(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mxhtmlnp.proxies.Attribute> node_attribute)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (mxhtmlnp.proxies.Attribute proxyObject : node_attribute)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Node_Attribute.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxhtmlnp.proxies.Node that = (mxhtmlnp.proxies.Node) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxHTMLNP.Node";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
